### ISSUE TITLE
datapicker model update

### ISSUE THREAD

**Issue by 111crb111** [AmiliaApp/backform#16]
Hi, thanks for awesome work i like that lib :).
Found some issue, when i change date in input, not pick from picker, model does not update on last number so i clear input by backspace and in model still 1 number when input is clear. and if i mark all input and press dell then blur from field model not updated value still in model.
I find solution for myself but maybe you make someting better.
My solution and events to DatepickerControl:
```javascript
    events: {
      "blur input": "onChange",
      "change input": "onChange", //blur not work in some situation so better add change event too
      "changeDate input": "onChange",
      "focus input": "clearInvalid"
    },
```
Hope you understand my awesome english :)

**Comment by martindrapeau** [comment]
Great fix. I added those missing events. Thanks for spotting.
