### ISSUE TITLE
Select / Option values are wrapped with double quotes

### ISSUE THREAD

**Issue by MihailRussu** [AmiliaApp/backform#29]
In all demos on https://amiliaapp.github.io/backform/ the values for Selects / Options are wrapped with two double quotes. Is there a reason for that? When serializing / submitting a form this causes wrong values to be sent to the server, i.e. in the demo, instead of `address.province=QC` - `address.province=%22QC%22` would be sent (tested in both IE and latest Chrome). 

See screenshot for a better explanation:

![double_quotes](https://cloud.githubusercontent.com/assets/1810455/8794896/7898d626-2f90-11e5-8b80-6c4c87059205.png)

**Comment by martindrapeau** [comment]
Data is stored as JSON in the value attributes. Forms are never sent as is. Instead, it is the serialized JSON model which is sent to the server via model.save(). The payload is sent as JSON.
