### ISSUE TITLE
Per-field override of controlLabelClassName, controlsClassName variables

### ISSUE THREAD

**Issue by jeff-h** [AmiliaApp/backform#38]
I need one of the forms in my app to present the fields differently than the other forms. The only way I could see to do this was to modify the `Backform` object immediately prior to instantiating each `Form`, every time I generate a form.

e.g.

```js
    _.extend(Backform, {
      controlLabelClassName: "control-label col-sm-12",
      controlsClassName: "col-sm-12",
    });

    this.loginForm = new Backform.Form({
```

In my case it would be nice to be able to override this per-form, but I could imagine a form with a more complex layout requiring this to even be per-field. Is there a better way of doing this currently that I'm missing?

**Comment by martindrapeau** [comment]
That is a good point. Each control refers to the global Backform namespace. In hindsight, that is poor design. It would be worthwhile moving that per form and even per control. The best would be for each control to have a resolver function that would handle that.

In the meantime, your solution works - but probably breaks when you re-render the form later.

The other option is to sub-class your controls and modify the template like this:
```
var myClasses = {
      controlLabelClassName: "control-label col-sm-12",
      controlsClassName: "col-sm-12"
};

var MyInputControl = Backfrom.InputControl.extend({
    template: _.template([
      '<label class="<%=myClasses.controlLabelClassName || Backform.controlLabelClassName%>"><%=label%></label>',
      '<div class="<%=myClasses.controlsClassName|| Backform.controlsClassName%>">',
      '  <input type="<%=type%>" class="<%=myClasses.controlClassName|| Backform.controlClassName%> <%=extraClasses.join(\' \')%>" name="<%=name%>" maxlength="<%=maxlength%>" value="<%-value%>" placeholder="<%-placeholder%>" <%=disabled ? "disabled" : ""%> <%=required ? "required" : ""%> />',
      '  <% if (helpMessage && helpMessage.length) { %>',
      '    <span class="<%=myClasses.helpMessageClassName|| Backform.helpMessageClassName%>"><%=helpMessage%></span>',
      '  <% } %>',
      '</div>'
    ].join("\n")),
});
```

**Comment by jeff-h** [comment]
Thanks for your comments. I'll close this to keep your issue queue clean, and because you've presented a workaround, but if I can cast my vote for a per-form and/or per-control resolver function that would be awesome :)
