### ISSUE TITLE
support for JSON Schema compliant fields

### ISSUE THREAD

**Issue by fuhrysteve** [AmiliaApp/backform#42]
I was wondering if you would be open to supporting [JSON Schema](http://json-schema.org) compliant schemas if passed in as an alternative format to the `fields` parameter.

The reason this would be valuable is JSON Schema is a cross platform specification, and so schemas written in other languages could be converted to JSON Schema and passed into `backform` automatically.

Here's an example of how this might look from an implementation standpoint:

```javascript
var jsonschema = {
  "properties": {
    "age": {
      "title": "age",
      "type": "number"
    },
    "balance": {
      "title": "balance",
      "type": "number"
    },
    "birthdate": {
      "format": "date",
      "title": "birthdate",
      "type": "string"
    },
    "created": {
      "format": "date-time",
      "title": "created",
      "type": "string"
    },
    "created_formatted": {
      "format": "date-time",
      "title": "created",
      "type": "string"
    },
    "created_iso": {
      "format": "date-time",
      "title": "created",
      "type": "string"
    },
    "email": {
      "title": "email",
      "type": "string"
    },
    "finger_count": {
      "title": "finger_count",
      "type": "integer"
    },
    "hair_colors": {
      "title": "hair_colors",
      "type": "array"
    },
    "homepage": {
      "title": "homepage",
      "type": "string"
    },
    "id": {
      "default": "no-id",
      "title": "id",
      "type": "string"
    },
    "name": {
      "title": "name",
      "type": "string"
    },
    "registered": {
      "title": "registered",
      "type": "boolean"
    },
    "sex": {
      "title": "sex",
      "type": "string"
    },
    "sex_choices": {
      "title": "sex_choices",
      "type": "array"
    },
    "since_created": {
      "title": "since_created",
      "type": "string"
    },
    "species": {
      "title": "SPECIES",
      "type": "string"
    },
    "time_registered": {
      "format": "time",
      "title": "time_registered",
      "type": "string"
    },
    "uid": {
      "title": "uid",
      "type": "string"
    },
    "updated": {
      "format": "date-time",
      "title": "updated",
      "type": "string"
    },
    "updated_local": {
      "format": "date-time",
      "title": "updated",
      "type": "string"
    },
    "various_data": {
      "title": "various_data",
      "type": "object"
    }
  },
  "required": [
    "name"
  ],
  "type": "object"
}

var form = new Backform.Form({
  el: $("#form"),
  model: user,
  fields: jsonschema
});
```

I think one could employ a `Object.prototype.toString.call(this.fields) === '[object Array]'` check [here](https://github.com/AmiliaApp/backform/blob/a69cf8e93e9cc229840ca510b8575cfbeddb6d79/src/backform.js#L114) to determine whether the user is implementing a `backform` native schema vs a JSON Schema.

Thanks for taking the time to review this. I'd be happy to submit a pull request for review if the idea is palatable to you.

**Comment by martindrapeau** [comment]
Hi Steven,

Thanks for your proposal. I've discussed with team members here at Amilia. Our first question is the use case. When would you use this? What value would it bring?

I imagine you will be providing a JSON Schema to Backform translator in that function. How will you know what control to map to? For instance, a select vs radio buttons.

**Comment by fuhrysteve** [comment]
Hi @martindrapeau, thanks for your consideration.

Imagine you are a developer at Ebay, and need to manage forms for various shipping modules: UPS, FedEx, John's Shipping Company, USPS, etc. Imagine also that UPS has different required fields for creating an equivalent shipping label than FedEx does. Somewhere, these "available options / required fields" for each shipping module need to be defined, and hopefully the system is designed such that the available fields can be expressed in one central place.

I am facing a similar scenario where I have a number of schemas defined in python that express various "available options" for configuring various systems (in many ways, similar to the Ebay example).

In my case, I am using a library called `marshmallow` to define my server-side schemas in python, and my client is a browser which only understands javascript & html. Here is the basic flow:

1. Define schema in marshmallow (on this page there are a handful of examples of the types of schemas this particular library allows you to craft) http://marshmallow.readthedocs.org/en/latest/examples.html
2. Convert the schema to a json-schema draft v4 compliant schema (I actually authored this little library: https://github.com/fuhrysteve/marshmallow-jsonschema#example-usage )
3. Provide that schema via some sort of `REST` api call (i.e. `/api/schema/myschema`)
4. `backform`, which has no knowledge of marshmallow or python (but can understand JSON!) renders the form in `HTML`

**Comment by fuhrysteve** [comment]
The alternative to building support directly into `backform` would be to write some sort of mapper function which loops through each property in my json-schema and expressing each one like a `backform` field.

**Comment by martindrapeau** [comment]
Hi @fuhrysteve,

That makes sense. If I understand properly, you intend to provide Backform a basic JSON Schema translator. Might want to make that extendible, like everything else. Sure, have a hack at it and we'll review your pull request. I think it will be a nice addition.

--Martin

**Comment by fuhrysteve** [comment]
Very cool, thanks! I'll see what we come up with over here prototyping it and how well it seems to mesh with backform's infrastructure. I'll go ahead and close this for now
